FROM httpd:alpine

COPY vs-apache/config/apache.conf /usr/local/apache2/conf/httpd.conf
COPY common-config/apache-error-codes.conf /usr/local/apache2/conf/error-codes.conf
COPY common-config/apache-error-redirects.conf /usr/local/apache2/conf/error-redirects.conf
